# Generated by Django 4.1 on 2022-08-07 02:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_note_model_delete_post_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_model',
            name='note_desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
