# Generated by Django 4.1 on 2022-08-07 05:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_user', models.CharField(max_length=255)),
                ('post_title', models.CharField(max_length=255)),
                ('post_desc', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
